(* Created by Wolfram Mathematica 10.0 : www.wolfram.com *)
Import["CompatTests.m"]; 
TapSuite[TapComment["Attributes for an existing symbol: "], 
 TapTestSame[Attributes[Plus], {Flat, Listable, NumericFunction, OneIdentity, 
   Orderless, Protected}], TapComment["Set attributes for a new symbol: "], 
 TapTestSame[Attributes[f] = {Listable, Protected}, {Listable, Protected}], 
 TapTestSame[Attributes[f], {Listable, Protected}], 
 TapComment["Attributes of a symbol:"], TapTestSame[Attributes[Plus], 
  {Flat, Listable, NumericFunction, OneIdentity, Orderless, Protected}], 
 TapComment["Attributes of several symbols in a list:"], 
 TapTestSame[Attributes[{Plus, Minus}], 
  {{Flat, Listable, NumericFunction, OneIdentity, Orderless, Protected}, 
   {Listable, NumericFunction, Protected}}], 
 TapComment["The symbol can be given as a string:"], 
 TapTestSame[Attributes["Set"], {HoldFirst, Protected, SequenceHold}], 
 TapTestSameBROKEN[Attributes[{f, g}], {{HoldAll, Listable}, {HoldAll}}], 
 TapTestSameBROKEN[Attributes[f] = {Listable}, Attributes[f] = {Listable}], 
 TapTestSameBROKEN[Attributes[f], {Protected}], 
 TapTestSameBROKEN[Attributes[f], {}], TapComment["RefLink[Attributes,paclet:\
ref/Attributes] has the attribute RefLink[HoldAll,paclet:ref/HoldAll]:"], 
 TapTestSame[Attributes[Attributes], {HoldAll, Listable, Protected}], 
 TapComment["This gives the attributes of the symbol syms itself:"], 
 TapTestSame[Attributes[syms], {}], 
 TapComment["This gives the attributes of all symbols in the list syms:"], 
 TapTestSameBROKEN[Attributes[Evaluate[syms]], 
  {{Flat, Listable, NumericFunction, OneIdentity, Orderless, Protected}, 
   {Flat, Listable, NumericFunction, OneIdentity, Orderless, Protected}, 
   {Listable, NumericFunction, OneIdentity, Protected}}]]
