(* Created by Wolfram Mathematica 10.0 : www.wolfram.com *)
Import["CompatTests.m"]; 
TapSuite[TapTestSame[77/11, 7], 
 TapComment["Enter in 2D form using Control+/:"], TapTestSame[77/11, 7], 
 TapComment[
  "RefLink[Divide,paclet:ref/Divide] reduces fractions to lowest terms:"], 
 TapTestSame[616/33, 56/3], 
 TapComment[
  "Force a numerical result by including a decimal point in the input:"], 
 TapTestSameBROKEN[616./33, 18.6667], 
 TapComment["/ is applied sequentially:"], TapTestSame[a/b/c/d, a/(b*c*d)], 
 TapComment["x/y is always converted to products and powers:"], 
 TapTestSameBROKEN[FullForm[a^2/b^3], a^2/b^3], 
 TapComment["Enter / using Esc\\[ThinSpace]div\\[ThinSpace]Esc:"], 
 TapTestSame[20/4, 5], TapComment[
  "RefLink[Divide,paclet:ref/Divide] threads element-wise over lists:"], 
 TapTestSame[{2, 3, 4, 5}/3, {2/3, 1, 4/3, 5/3}], 
 TapTestSame[{x, y, z}/{a, b, c}, {x/a, y/b, z/c}], 
 TapTestSame[FoldList[Divide, 1, Range[10]], {1, 1, 1/2, 1/6, 1/24, 1/120, 
   1/720, 1/5040, 1/40320, 1/362880, 1/3628800}], 
 TapComment["Successive ratios in a list:"], 
 TapTestSame[Apply[Divide, Partition[{a, b, c, d, e}, 2, 1], {1}], 
  {a/b, b/c, c/d, d/e}], TapComment["Expand quotients:"], 
 TapTestSame[(x + y)/z, (x + y)/z], TapTestSameBROKEN[Expand[%], x/z + y/z], 
 TapComment["Cancel common factors in rational expressions:"], 
 TapTestSame[Cancel[(1 - x^2)/(1 - x)], 1 + x], 
 TapComment["Split into partial fractions:"], TapTestSame[Apart[1/(x^2 - 1)], 
  1/(2*(-1 + x)) - 1/(2*(1 + x))], TapTestSame[1/0, ComplexInfinity], 
 TapTestSame[0/0, Indeterminate], TapTestSame[1/Infinity, 0], 
 TapComment[
  "Pattern matching relies on RefLink[FullForm,paclet:ref/FullForm]:"], 
 TapTestSame[Replace[x^2/y^3, (a_)/(b_) -> f[a, b]], x^2/y^3], 
 TapTestSameBROKEN[FullForm[x^2/y^3], x^2/y^3], 
 TapTestSame[Replace[x^2/y^3, (a:_^(_.))*(b:_^(_.)) -> f[a, b]], 
  f[x^2, 1/y^3]], TapTestSame[NestList[1/(1 + #1) & , x, 5], 
  {x, 1/(1 + x), 1/(1 + 1/(1 + x)), 1/(1 + 1/(1 + 1/(1 + x))), 
   1/(1 + 1/(1 + 1/(1 + 1/(1 + x)))), 
   1/(1 + 1/(1 + 1/(1 + 1/(1 + 1/(1 + x)))))}], 
 TapComment["Array of possible fractions:"], 
 TapTestSame[Array[Divide, {4, 4}], {{1, 1/2, 1/3, 1/4}, {2, 1, 2/3, 1/2}, 
   {3, 3/2, 1, 3/4}, {4, 2, 4/3, 1}}], 
 TapComment["Integers that divide exactly:"], 
 TapTestSameBROKEN[HoldComplete[ListPlot[Position[Array[Divide, {20, 20}], 
     _Integer]]], $Failed]]
