(* Created by Wolfram Mathematica 10.0 : www.wolfram.com *)
Import["CompatTests.m"]; 
ESimpleExamples[ESameTest[MapIndexed[f, {a, b, c, d}], 
  {f[a, {1}], f[b, {2}], f[c, {3}], f[d, {4}]}], 
 EComment["#2 gives the indices of each part:"], 
 ESameTest[MapIndexed[First[#2] + f[#1] & , {a, b, c, d}], 
  {1 + f[a], 2 + f[b], 3 + f[c], 4 + f[d]}], 
 ESameTest[MapIndexed[f, {{a, b}, {c, d, e}}], 
  {f[{a, b}, {1}], f[{c, d, e}, {2}]}], 
 ESameTest[MapIndexed[f, {{a, b}, {c, d, e}}, {2}], 
  {{f[a, {1, 1}], f[b, {1, 2}]}, {f[c, {2, 1}], f[d, {2, 2}], 
    f[e, {2, 3}]}}], EComment["Map over an association:"], 
 ESameTestBROKEN[MapIndexed[f, \[LeftAssociation] "a" -> 1, a -> 2, 
    1 -> 1 \[RightAssociation]], \[LeftAssociation] a -> f[1, {Key[a]}], 
   a -> f[2, {Key[a]}], 1 -> f[1, {Key[1]}] \[RightAssociation]], 
 EComment["Map over nested associations:"], 
 ESameTest[MapIndexed[h, \[LeftAssociation] 
    a -> \[LeftAssociation] b -> c, p -> \[LeftAssociation] 
        q -> r \[RightAssociation] \[RightAssociation], 
    d -> {e} \[RightAssociation], {2}], \[LeftAssociation] 
   a -> \[LeftAssociation] b -> h[c, {Key[a], Key[b]}], 
     p -> h[\[LeftAssociation] q -> r \[RightAssociation], 
       {Key[a], Key[p]}] \[RightAssociation], 
   d -> {h[e, {Key[d], 1}]} \[RightAssociation]], 
 EComment[
  "Use the operator form of RefLink[MapIndexed,paclet:ref/MapIndexed]:"], 
 ESameTestBROKEN[MapIndexed[f][{a, b, c, d}], {f[a, {1}], f[b, {2}], 
   f[c, {3}], f[d, {4}]}], EComment["Map at level 1 (default):"], 
 ESameTest[MapIndexed[f, {{{{{a}}}}}], {f[{{{{a}}}}, {1}]}], 
 EComment["Map down to level 2:"], ESameTest[MapIndexed[f, {{{{{a}}}}}, 2], 
  {f[{f[{{{a}}}, {1, 1}]}, {1}]}], EComment["Map at level 2:"], 
 ESameTest[MapIndexed[f, {{{{{a}}}}}, {2}], {{f[{{{a}}}, {1, 1}]}}], 
 EComment["Map down to level 3:"], ESameTest[MapIndexed[f, {{{{{a}}}}}, 3], 
  {f[{f[{f[{{a}}, {1, 1, 1}]}, {1, 1}]}, {1}]}], 
 EComment["Map onto all elements of an expression:"], 
 ESameTest[MapIndexed[f, {{a, b}, {c, d, {e}}}, Infinity], 
  {f[{f[a, {1, 1}], f[b, {1, 2}]}, {1}], 
   f[{f[c, {2, 1}], f[d, {2, 2}], f[{f[e, {2, 3, 1}]}, {2, 3}]}, {2}]}], 
 EComment["Map only onto the \"leaves\" of the expression:"], 
 ESameTest[MapIndexed[f, {{a, b}, {c, d, {e}}}, {-1}], 
  {{f[a, {1, 1}], f[b, {1, 2}]}, {f[c, {2, 1}], f[d, {2, 2}], 
    {f[e, {2, 3, 1}]}}}], EComment["Negative levels:"], 
 ESameTest[MapIndexed[f, {{{{a}}}}, -1], 
  {f[{f[{f[{f[a, {1, 1, 1, 1}]}, {1, 1, 1}]}, {1, 1}]}, {1}]}], 
 ESameTest[MapIndexed[f, {{{{a}}}}, -2], 
  {f[{f[{f[{a}, {1, 1, 1}]}, {1, 1}]}, {1}]}], 
 ESameTest[MapIndexed[f, {{{{a}}}}, -3], {f[{f[{{a}}, {1, 1}]}, {1}]}], 
 EComment["Different heads at each level:"], 
 ESameTest[MapIndexed[f, h0[h1[h2[h3[h4[a]]]]], {2, -3}], 
  h0[h1[f[h2[f[h3[h4[a]], {1, 1, 1}]], {1, 1}]]]], 
 EComment["Map on levels 0 through 1; the head has index {}:"], 
 ESameTest[MapIndexed[f, {a, b}, {0, 1}], f[{f[a, {1}], f[b, {2}]}, {}]], 
 EComment["RefLink[MapIndexed,paclet:ref/MapIndexed] can be used on \
expressions with any head:"], ESameTest[MapIndexed[f, a + b + c + d], 
  f[a, {1}] + f[b, {2}] + f[c, {3}] + f[d, {4}]], 
 EComment["The function can be mapped onto the heads as well:"], 
 ESameTest[MapIndexed[f, {a, b, c}, Heads -> True], 
  f[List, {0}][f[a, {1}], f[b, {2}], f[c, {3}]]], 
 EComment[
  "RefLink[MapIndexed,paclet:ref/MapIndexed] works on sparse arrays:"], 
 ESameTest[MapIndexed[f, SparseArray[3 -> a, 5]], 
  {f[0, {1}], f[0, {2}], f[a, {3}], f[0, {4}], f[0, {5}]}], 
 EComment["By default, the function is not mapped onto the heads:"], 
 ESameTest[MapIndexed[f, {a, b, c}], {f[a, {1}], f[b, {2}], f[c, {3}]}], 
 ESameTest[MapIndexed[f, {a, b, c}, Heads -> True], 
  f[List, {0}][f[a, {1}], f[b, {2}], f[c, {3}]]], 
 EComment["Map onto the heads at all levels:"], 
 ESameTest[MapIndexed[f, p[x][a, b, c], Infinity, Heads -> True], 
  f[f[p, {0, 0}][f[x, {0, 1}]], {0}][f[a, {1}], f[b, {2}], f[c, {3}]]], 
 EComment["Label parts by position:"], 
 ESameTestBROKEN[MapIndexed[Labeled, {x^2, x + y, y^2, y^3}], 
  {x^2*{1}, x + y*{2}, y^2*{3}, y^3*{4}}], 
 ESameTestBROKEN[HoldComplete[MapIndexed[Framed[Labeled[#1, #2]] & , 
    {x^2, x + y, y^2, y^3}, Infinity]], $Failed], 
 EComment["Use tooltips to show part numbers of subexpressions:"], 
 ESameTestBROKEN[MapIndexed[Tooltip, Integrate[1/(x^4 - 1), x], Infinity], 
  (-(1/2))*ArcTan[x] + (1/4)*Log[-1 + x] + (-(1/4))*Log[1 + x]], 
 EComment["Convert a list to a polynomial:"], 
 ESameTest[Total[MapIndexed[#1*x^First[#2] & , {a, b, c, d, e}]], 
  a*x + b*x^2 + c*x^3 + d*x^4 + e*x^5], 
 EComment["Rotate lists based on position:"], 
 ESameTest[MapIndexed[RotateLeft, Table[{a, b, c}, {6}]], 
  {{b, c, a}, {c, a, b}, {a, b, c}, {b, c, a}, {c, a, b}, {a, b, c}}], 
 ESameTestBROKEN[HoldComplete[MatrixForm[MapIndexed[RotateLeft, 
     Table[{{a, b}, {c, d}}, {3}, {3}], {2}]]], $Failed], 
 EComment["Obtain a list of all parts in an expression:"], 
 ESameTest[First[Last[Reap[MapIndexed[Sow[#2] & , {{a, b}, {c}, {{d}}}, 
      {1, Infinity}]]]], {{1, 1}, {1, 2}, {1}, {2, 1}, {2}, {3, 1, 1}, 
   {3, 1}, {3}}], ESameTest[Position[{{a, b}, {c}, {{d}}}, _, Infinity, 
   Heads -> False], {{1, 1}, {1, 2}, {1}, {2, 1}, {2}, {3, 1, 1}, {3, 1}, 
   {3}}], EComment["Using only the first argument is equivalent to using \
RefLink[Map,paclet:ref/Map]:"], ESameTest[MapIndexed[f[#1] & , {a, b, c}], 
  {f[a], f[b], f[c]}], ESameTest[f /@ {a, b, c}, {f[a], f[b], f[c]}]]
