(* Created by Wolfram Mathematica 10.0 : www.wolfram.com *)
Import["CompatTests.m"]; 
ESimpleExamples[EComment[
  "# represents the first argument of a pure function:"], 
 ESameTest[(f[#1, a, #1, b] & )[x, y], f[x, a, x, b]], 
 EComment["Use numbered arguments:"], 
 ESameTest[(f[#1, #2, #1, #3] & )[x, y, z], f[x, y, x, z]], 
 EComment["Used named arguments from an association:"], 
 ESameTestBROKEN[(f[u, v, u] & )[\[LeftAssociation] "u" -> x, 
    "v" -> y \[RightAssociation]], f[x, y, x]], 
 EComment["# is short for #1, the first argument:"], 
 ESameTest[(#1 & )[1, 2, 3], 1], ESameTest[(#1 & )[1, 2, 3], 1], 
 EComment["#name is effectively a short form of #[\"name\"]:"], 
 ESameTestBROKEN[(x & )[\[LeftAssociation] "x" -> a, 
    "y" -> b \[RightAssociation]], a], 
 ESameTest[(#1["x"] & )[\[LeftAssociation] "x" -> a, 
    "y" -> b \[RightAssociation]], a], 
 EComment[
  "#name is interpreted as RefLink[Slot,paclet:ref/Slot][\"name\"]:"], 
 ESameTestBROKEN[FullForm[z & ], Slot["z"] & ], 
 EComment["#name always refers to the association in the first argument:"], 
 ESameTestBROKEN[(y & )[\[LeftAssociation] "x" -> 1, 
    "y" -> 2 \[RightAssociation], \[LeftAssociation] "x" -> 3, 
    "y" -> 4 \[RightAssociation]], 2], 
 EComment["Extract from an association slot other than the first:"], 
 ESameTest[(#2["y"] & )[\[LeftAssociation] "x" -> 1, 
    "y" -> 2 \[RightAssociation], \[LeftAssociation] "x" -> 3, 
    "y" -> 4 \[RightAssociation]], 4], 
 EComment["#0 stands for the whole pure function:"], 
 ESameTest[(f[#0] & )[x], f[f[#0] & ]], 
 EComment["Programmatically create a pure function of 5 arguments:"], 
 ESameTest[Evaluate[f @@ Array[Slot, 5]] & , f[#1, #2, #3, #4, #5] & ], 
 ESameTestBROKEN[% @@ Range[10], f[1, 2, 3, 4, 5]], 
 EComment[
  "# allows function arguments to be referenced without giving them names:"], 
 ESameTest[Function[u, 1 + u][x], 1 + x], ESameTest[(1 + #1 & )[x], 1 + x], 
 EComment["Additional arguments are ignored:"], 
 ESameTest[(f[#1, #2] & )[a, b, c, d], f[a, b]], 
 EComment["## stands for the sequence of all arguments:"], 
 ESameTest[({#1, #2, #3} & )[a, b, c], {a, b, c}], 
 ESameTest[({##1} & )[a, b, c], {a, b, c}], 
 EComment["Use explicit names to set up nested pure functions:"], 
 ESameTest[Function[u, Function[v, f[u, v]]][x], Function[v$, f[x, v$]]], 
 ESameTest[Function[u, Function[v, f[u, v]]][x][y], f[x, y]], 
 EComment["Use # for the inner function:"], 
 ESameTest[Function[u, f[u, #1] & ][x], f[x, #1] & ], 
 ESameTest[Function[u, f[u, #1] & ][x][y], f[x, y]], 
 EComment["Use # for the outer function: "], 
 ESameTest[(Function[v, f[#1, v]] & )[x], Function[v, f[x, v]]], 
 ESameTest[(Function[v, f[#1, v]] & )[x][y], f[x, y]], 
 EComment["Using nested # notation behaves differently:"], 
 ESameTest[((f[#1, #1] & ) & )[x], f[#1, #1] & ], 
 ESameTest[((f[#1, #1] & ) & )[x][y], f[y, y]], 
 EComment["If too few arguments are provided, a message is generated:"], 
 ESameTest[(f[#4] & )[a, b, c], f[#4]], ESameTest[(f[#4] & )[a, b, c, d], 
  f[d]], EComment["A space between # and the following token will be \
interpreted as multiplication:"], ESameTestBROKEN[InputForm[#1*2], 2*#1], 
 ESameTestBROKEN[InputForm[#1*name], name*#1], 
 EComment["A recursive definition for factorial using #0:"], 
 ESameTest[f = If[#1 == 1, 1, #1*#0[#1 - 1]] & , 
  If[#1 == 1, 1, #1*#0[#1 - 1]] & ], ESameTest[f[10], 3628800], 
 ESameTest[10!, 3628800]]
